### ISSUE TITLE
Using "next" NPM packages would allow using latest Gatsby releases

### ISSUE THREAD

**Issue by PEM--** [fabe/gatsby-universal#11]
In `package.json`, using something like:
```
...
    "gatsby": "next",
    "gatsby-image": "next",
    "gatsby-plugin-offline": "next",
    "gatsby-plugin-react-helmet": "next",
    "gatsby-plugin-sharp": "next",
    "gatsby-plugin-sitemap": "next",
...
```
would allow using latest Gatsby v2 releases.

If you want, I can PR it easily.

**Comment by fabe** [comment]
Hey, thanks for your feedback! I lock the gatsby versions because I want to make sure things don't break after a fresh install. There were some breaking changes e.g. to the routing during the beta phase that would've completely broken the site out of the blue. Plus, Gatsby v2 will be out of beta very shortly 👍

**Comment by PEM--** [comment]
OK, thanks for the starter. It's very easy to work with 👍

**Comment by fabe** [comment]
Happy to hear that! Let me know if you have any other feedback or suggestions!
